default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: my_animes_development
  username: postgres
  password: postgres
  host: localhost
test:
  <<: *default
  database: my_animes_test
  username: postgres
  password: postgres
  host: localhost

production:
  <<: *default
  database: my_animes_production
  username: postgres
  password: postgres
